version: "3.8"

services:
    mariadb:
        image: mariadb:latest
        hostname: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./scripts:/docker-entrypoint-initdb.d
    prometheus:
        image: prom/prometheus:latest
        hostname: prometheus
        depends_on:
            - mysqld-exporter
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    mysqld-exporter:
        image: prom/mysqld-exporter:latest
        hostname: mysqld-exporter
        depends_on:
            - mariadb
        ports:
            - 9104:9104
        environment:
            DATA_SOURCE_NAME: "root:password@(mariadb:3306)/test"
